repositories:
- name: jetstack
  url: https://charts.jetstack.io

releases:
- name: cert-manager
  chart: jetstack/cert-manager
  version: 1.1.0
  namespace: cert-manager
  set:
    installCRDs: true
  hooks:
    - events: ["presync"]
      command: "kubectl"
      args: ["label", "namespace", "cert-manager", "certmanager.k8s.io/disable-validation=true"]